src/java/be/demo/HelloController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.demo;

import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author MTJAH17
 */
@Named
@RequestScoped
public class HelloController implements Serializable{
    
    private String name;
    
    @Inject
    private GreetingService greetingService;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getGreetingFromBusinessLayer(){
        return "greeting: "+greetingService.sayHello();
    }
}

web/hello.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello #{helloController.name}<br />
        #{helloController.greetingFromBusinessLayer}
    </h:body>
</html>


web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            naam: <h:inputText value="#{helloController.name}"></h:inputText>
            <h:commandButton value="Say hello" action="hello"></h:commandButton>
        </h:form>
    </h:body>
</html>